import { AlgorithmType } from '../types';

export interface CppCodeDefinition {
  algorithm: AlgorithmType;
  title: string;
  lines: string[];
}

export const CPP_ALGORITHM_CODES: Record<AlgorithmType, CppCodeDefinition> = {
  bfs: {
    algorithm: 'bfs',
    title: 'Breadth-First Search (BFS)',
    lines: [
      'void bfs(int start, const vector<vector<int>>& adj, int n) {',
      '    vector<bool> visited(n, false);',
      '    queue<int> q;',
      '    ',
      '    visited[start] = true;',
      '    q.push(start);',
      '    ',
      '    while (!q.empty()) {',
      '        int u = q.front();',
      '        q.pop();',
      '        // Process node u',
      '        ',
      '        for (int v : adj[u]) {',
      '            if (!visited[v]) {',
      '                visited[v] = true;',
      '                q.push(v);',
      '            }',
      '        }',
      '    }',
      '}'
    ]
  },

  dfs: {
    algorithm: 'dfs',
    title: 'Depth-First Search (DFS)',
    lines: [
      'void dfs(int u, const vector<vector<int>>& adj, vector<bool>& visited) {',
      '    visited[u] = true;',
      '    // Enter node u (call stack pushes u)',
      '    ',
      '    for (int v : adj[u]) {',
      '        if (!visited[v]) {',
      '            // Traverse tree edge (u -> v)',
      '            dfs(v, adj, visited);',
      '        }',
      '    }',
      '    // Backtrack from node u',
      '}',
      '',
      'void run_dfs(int start, const vector<vector<int>>& adj, int n) {',
      '    vector<bool> visited(n, false);',
      '    dfs(start, adj, visited);',
      '}'
    ]
  },

  dijkstra: {
    algorithm: 'dijkstra',
    title: "Dijkstra's Shortest Path Algorithm",
    lines: [
      'vector<int> dijkstra(int start, const vector<vector<pair<int,int>>>& adj, int n) {',
      '    vector<int> dist(n, INF);',
      '    priority_queue<pair<int,int>, vector<pair<int,int>>, greater<>> pq;',
      '    ',
      '    dist[start] = 0;',
      '    pq.push({0, start}); // {distance, node}',
      '    ',
      '    while (!pq.empty()) {',
      '        auto [d, u] = pq.top();',
      '        pq.pop();',
      '        ',
      '        if (d > dist[u]) continue; // Stale entry',
      '        ',
      '        for (auto& [v, weight] : adj[u]) {',
      '            if (dist[u] + weight < dist[v]) {',
      '                dist[v] = dist[u] + weight;',
      '                pq.push({dist[v], v});',
      '            }',
      '        }',
      '    }',
      '    return dist;',
      '}'
    ]
  },

  'bellman-ford': {
    algorithm: 'bellman-ford',
    title: 'Bellman-Ford Algorithm (with Negative Cycle Detection)',
    lines: [
      'bool bellmanFord(int src, int V, const vector<Edge>& edges, vector<int>& dist) {',
      '    dist.assign(V, INF);',
      '    dist[src] = 0;',
      '    ',
      '    // Relax all edges |V| - 1 times',
      '    for (int i = 1; i <= V - 1; ++i) {',
      '        bool any_updated = false;',
      '        for (const auto& e : edges) {',
      '            if (dist[e.u] != INF && dist[e.u] + e.w < dist[e.v]) {',
      '                dist[e.v] = dist[e.u] + e.w;',
      '                any_updated = true;',
      '            }',
      '        }',
      '        if (!any_updated) break;',
      '    }',
      '    ',
      '    // Check for negative-weight cycles (V-th pass)',
      '    for (const auto& e : edges) {',
      '        if (dist[e.u] != INF && dist[e.u] + e.w < dist[e.v]) {',
      '            return false; // Negative cycle detected!',
      '        }',
      '    }',
      '    return true; // Shortest distances valid',
      '}'
    ]
  },

  prim: {
    algorithm: 'prim',
    title: "Prim's Minimum Spanning Tree (MST)",
    lines: [
      'int primMST(int V, const vector<vector<pair<int,int>>>& adj) {',
      '    vector<bool> inMST(V, false);',
      '    priority_queue<tuple<int,int,int>, vector<tuple<int,int,int>>, greater<>> pq;',
      '    int mstWeight = 0;',
      '    ',
      '    // Start with node 0: {weight, u, v}',
      '    pq.push({0, 0, -1});',
      '    ',
      '    while (!pq.empty()) {',
      '        auto [w, u, p] = pq.top();',
      '        pq.pop();',
      '        ',
      '        if (inMST[u]) continue;',
      '        inMST[u] = true;',
      '        mstWeight += w;',
      '        ',
      '        for (auto& [v, weight] : adj[u]) {',
      '            if (!inMST[v]) {',
      '                pq.push({weight, v, u});',
      '            }',
      '        }',
      '    }',
      '    return mstWeight;',
      '}'
    ]
  },

  kruskal: {
    algorithm: 'kruskal',
    title: "Kruskal's MST Algorithm (Union-Find / DSU)",
    lines: [
      'int kruskalMST(int V, vector<Edge>& edges) {',
      '    sort(edges.begin(), edges.end(), [](const Edge& a, const Edge& b) {',
      '        return a.weight < b.weight;',
      '    });',
      '    DisjointSet dsu(V);',
      '    int mstWeight = 0, edgesCount = 0;',
      '    ',
      '    for (const auto& e : edges) {',
      '        int rootU = dsu.find(e.u);',
      '        int rootV = dsu.find(e.v);',
      '        ',
      '        if (rootU != rootV) {',
      '            dsu.unite(rootU, rootV);',
      '            mstWeight += e.weight;',
      '            edgesCount++;',
      '            if (edgesCount == V - 1) break;',
      '        }',
      '    }',
      '    return mstWeight;',
      '}'
    ]
  },

  toposort: {
    algorithm: 'toposort',
    title: "Topological Sort (Kahn's BFS Algorithm)",
    lines: [
      'vector<int> topologicalSort(int V, const vector<vector<int>>& adj) {',
      '    vector<int> inDegree(V, 0);',
      '    for (int u = 0; u < V; ++u)',
      '        for (int v : adj[u]) inDegree[v]++;',
      '    ',
      '    queue<int> q;',
      '    for (int i = 0; i < V; ++i)',
      '        if (inDegree[i] == 0) q.push(i);',
      '    ',
      '    vector<int> order;',
      '    while (!q.empty()) {',
      '        int u = q.front(); q.pop();',
      '        order.push_back(u);',
      '        ',
      '        for (int v : adj[u]) {',
      '            if (--inDegree[v] == 0) {',
      '                q.push(v);',
      '            }',
      '        }',
      '    }',
      '    return (order.size() == V) ? order : vector<int>(); // Cycle check',
      '}'
    ]
  },

  'cycle-undirected': {
    algorithm: 'cycle-undirected',
    title: 'Cycle Detection in Undirected Graph (BFS Parent Tracking)',
    lines: [
      'bool isCycleUndirectedBFS(int src, const vector<vector<int>>& adj, vector<bool>& vis) {',
      '    vis[src] = true;',
      '    queue<pair<int, int>> q; // {current_node, parent_node}',
      '    q.push({src, -1});',
      '    ',
      '    while (!q.empty()) {',
      '        auto [node, parent] = q.front();',
      '        q.pop();',
      '        ',
      '        for (int adjNode : adj[node]) {',
      '            if (!vis[adjNode]) {',
      '                vis[adjNode] = true;',
      '                q.push({adjNode, node});',
      '            } else if (adjNode != parent) {',
      '                return true; // Visited adjacent node is NOT parent -> Cycle detected!',
      '            }',
      '        }',
      '    }',
      '    return false;',
      '}'
    ]
  },

  'cycle-directed': {
    algorithm: 'cycle-directed',
    title: 'Cycle Detection in Directed Graph (DFS Recursion Stack)',
    lines: [
      'bool isCycleDirectedDFS(int u, const vector<vector<int>>& adj, vector<int>& vis, vector<int>& pathVis) {',
      '    vis[u] = 1;',
      '    pathVis[u] = 1; // Mark node in current active recursion stack',
      '    ',
      '    for (int v : adj[u]) {',
      '        if (!vis[v]) {',
      '            if (isCycleDirectedDFS(v, adj, vis, pathVis)) return true;',
      '        } else if (pathVis[v]) {',
      '            return true; // Back-edge detected! Points to node in active path -> Cycle!',
      '        }',
      '    }',
      '    ',
      '    pathVis[u] = 0; // Backtrack: remove node from recursion stack',
      '    return false;',
      '}'
    ]
  },

  'cycle-detection': {
    algorithm: 'cycle-detection',
    title: 'Cycle Detection (Coloring DFS Algorithm)',
    lines: [
      'enum State { UNVISITED, VISITING, VISITED };',
      '',
      'bool hasCycleDFS(int u, const vector<vector<int>>& adj, vector<State>& state) {',
      '    state[u] = VISITING; // Gray: in current recursion call stack',
      '    ',
      '    for (int v : adj[u]) {',
      '        if (state[v] == VISITING) {',
      '            return true; // Found back-edge to ancestor -> Cycle detected!',
      '        }',
      '        if (state[v] == UNVISITED && hasCycleDFS(v, adj, state)) {',
      '            return true;',
      '        }',
      '    }',
      '    ',
      '    state[u] = VISITED; // Black: processed fully',
      '    return false;',
      '}'
    ]
  },

  'circle-of-strings': {
    algorithm: 'circle-of-strings',
    title: 'Circle of Strings (Eulerian Circuit on Character Graph)',
    lines: [
      'bool isCircleOfStrings(int n, const vector<string>& words) {',
      '    vector<int> inDegree(26, 0), outDegree(26, 0);',
      '    vector<vector<int>> adj(26);',
      '    ',
      '    for (const string& w : words) {',
      '        int u = w.front() - \'a\', v = w.back() - \'a\';',
      '        outDegree[u]++;',
      '        inDegree[v]++;',
      '        adj[u].push_back(v); // Directed edge from first to last char',
      '    }',
      '    ',
      '    // Condition 1: In-degree must equal Out-degree for every vertex',
      '    for (int i = 0; i < 26; ++i) {',
      '        if (inDegree[i] != outDegree[i]) return false;',
      '    }',
      '    ',
      '    // Condition 2: All non-zero degree vertices must form a single SCC',
      '    return isStronglyConnected(26, adj);',
      '}'
    ]
  },

  kosaraju: {
    algorithm: 'kosaraju',
    title: "Kosaraju's Strongly Connected Components (SCC)",
    lines: [
      'void fillOrder(int u, const vector<vector<int>>& adj, vector<bool>& vis, stack<int>& st) {',
      '    vis[u] = true;',
      '    for (int v : adj[u]) if (!vis[v]) fillOrder(v, adj, vis, st);',
      '    st.push(u); // Push to stack upon finishing',
      '}',
      '',
      'void dfsRev(int u, const vector<vector<int>>& revAdj, vector<bool>& vis, vector<int>& scc) {',
      '    vis[u] = true;',
      '    scc.push_back(u);',
      '    for (int v : revAdj[u]) if (!vis[v]) dfsRev(v, revAdj, vis, scc);',
      '}',
      '',
      'vector<vector<int>> kosarajuSCC(int V, const vector<vector<int>>& adj) {',
      '    stack<int> st;',
      '    vector<bool> vis(V, false);',
      '    // Phase 1: Forward DFS fill finish times',
      '    for (int i = 0; i < V; ++i) if (!vis[i]) fillOrder(i, adj, vis, st);',
      '    ',
      '    // Phase 2: Transpose graph (reverse all edges)',
      '    auto revAdj = getTranspose(V, adj);',
      '    fill(vis.begin(), vis.end(), false);',
      '    ',
      '    // Phase 3: Pop stack and extract SCCs using reverse DFS',
      '    vector<vector<int>> components;',
      '    while (!st.empty()) {',
      '        int u = st.top(); st.pop();',
      '        if (!vis[u]) {',
      '            vector<int> scc;',
      '            dfsRev(u, revAdj, vis, scc);',
      '            components.push_back(scc);',
      '        }',
      '    }',
      '    return components;',
      '}'
    ]
  },

  'flood-fill': {
    algorithm: 'flood-fill',
    title: 'Flood Fill (Grid-Based BFS/DFS Exploration)',
    lines: [
      'void floodFill(vector<vector<int>>& grid, int sr, int sc, int newColor) {',
      '    int oldColor = grid[sr][sc];',
      '    if (oldColor == newColor) return;',
      '    ',
      '    int rows = grid.size(), cols = grid[0].size();',
      '    queue<pair<int,int>> q;',
      '    ',
      '    grid[sr][sc] = newColor;',
      '    q.push({sr, sc});',
      '    int dx[] = {-1, 1, 0, 0};',
      '    int dy[] = {0, 0, -1, 1};',
      '    ',
      '    while (!q.empty()) {',
      '        auto [r, c] = q.front(); q.pop();',
      '        ',
      '        for (int i = 0; i < 4; ++i) {',
      '            int nr = r + dx[i], nc = c + dy[i];',
      '            if (nr >= 0 && nr < rows && nc >= 0 && nc < cols && grid[nr][nc] == oldColor) {',
      '                grid[nr][nc] = newColor;',
      '                q.push({nr, nc});',
      '            }',
      '        }',
      '    }',
      '}'
    ]
  },

  'rotten-oranges': {
    algorithm: 'rotten-oranges',
    title: 'Rotting Oranges (Multi-Source BFS Spread)',
    lines: [
      'int orangesRotting(vector<vector<int>>& grid) {',
      '    int rows = grid.size(), cols = grid[0].size();',
      '    queue<pair<int, int>> q;',
      '    int freshCount = 0;',
      '    ',
      '    // 1. Collect all initial rotten oranges into Queue',
      '    for (int r = 0; r < rows; ++r) {',
      '        for (int c = 0; c < cols; ++c) {',
      '            if (grid[r][c] == 2) q.push({r, c});',
      '            else if (grid[r][c] == 1) freshCount++;',
      '        }',
      '    }',
      '    if (freshCount == 0) return 0;',
      '    ',
      '    int minutes = 0;',
      '    int dx[] = {-1, 1, 0, 0};',
      '    int dy[] = {0, 0, -1, 1};',
      '    ',
      '    // 2. Multi-source BFS layer-by-layer',
      '    while (!q.empty() && freshCount > 0) {',
      '        int sz = q.size();',
      '        for (int k = 0; k < sz; ++k) {',
      '            auto [r, c] = q.front(); q.pop();',
      '            for (int i = 0; i < 4; ++i) {',
      '                int nr = r + dx[i], nc = c + dy[i];',
      '                if (nr >= 0 && nr < rows && nc >= 0 && nc < cols && grid[nr][nc] == 1) {',
      '                    grid[nr][nc] = 2; // Rots adjacent fresh orange',
      '                    freshCount--;',
      '                    q.push({nr, nc});',
      '                }',
      '            }',
      '        }',
      '        minutes++;',
      '    }',
      '    return freshCount == 0 ? minutes : -1;',
      '}'
    ]
  },

  'critical-connections': {
    algorithm: 'critical-connections',
    title: "Tarjan's Bridge Detection (Critical Connections)",
    lines: [
      'void dfs_bridges(int u, int p, const vector<vector<int>>& adj,',
      '                 vector<int>& tin, vector<int>& low, int& timer,',
      '                 vector<pair<int, int>>& bridges) {',
      '    tin[u] = low[u] = ++timer;',
      '    ',
      '    for (int v : adj[u]) {',
      '        if (v == p) continue; // Skip edge to immediate parent',
      '        ',
      '        if (tin[v]) {',
      '            // Back-edge found: ancestor reached',
      '            low[u] = min(low[u], tin[v]);',
      '        } else {',
      '            // Tree edge: explore child subtree',
      '            dfs_bridges(v, u, adj, tin, low, timer, bridges);',
      '            low[u] = min(low[u], low[v]);',
      '            ',
      '            if (low[v] > tin[u]) {',
      '                // No back-edge from v subtree to u or above: Bridge!',
      '                bridges.push_back({u, v});',
      '            }',
      '        }',
      '    }',
      '}'
    ]
  },

  'articulation-points': {
    algorithm: 'articulation-points',
    title: "Tarjan's Articulation Points (Cut Vertices)",
    lines: [
      'void dfs_cut_vertices(int u, int p, const vector<vector<int>>& adj,',
      '                      vector<int>& tin, vector<int>& low, int& timer,',
      '                      vector<bool>& isCut) {',
      '    tin[u] = low[u] = ++timer;',
      '    int children = 0;',
      '    ',
      '    for (int v : adj[u]) {',
      '        if (v == p) continue;',
      '        ',
      '        if (tin[v]) {',
      '            low[u] = min(low[u], tin[v]);',
      '        } else {',
      '            dfs_cut_vertices(v, u, adj, tin, low, timer, isCut);',
      '            low[u] = min(low[u], low[v]);',
      '            ',
      '            if (low[v] >= tin[u] && p != -1) {',
      '                isCut[u] = true; // Non-root cut vertex',
      '            }',
      '            children++;',
      '        }',
      '    }',
      '    if (p == -1 && children > 1) {',
      '        isCut[u] = true; // Root cut vertex (>=2 children)',
      '    }',
      '}'
    ]
  },

  'network-connected': {
    algorithm: 'network-connected',
    title: 'Operations to Make Network Connected (LeetCode 1319)',
    lines: [
      'int makeConnected(int n, vector<vector<int>>& connections) {',
      '    if (connections.size() < n - 1) return -1; // Insufficient total cables',
      '    ',
      '    vector<vector<int>> adj(n);',
      '    for (auto& c : connections) {',
      '        adj[c[0]].push_back(c[1]);',
      '        adj[c[1]].push_back(c[0]);',
      '    }',
      '    ',
      '    vector<bool> visited(n, false);',
      '    int components = 0;',
      '    ',
      '    for (int i = 0; i < n; ++i) {',
      '        if (!visited[i]) {',
      '            components++;',
      '            dfs(i, adj, visited); // Discover connected computer cluster',
      '        }',
      '    }',
      '    ',
      '    return components - 1; // Minimum operations to rewire',
      '}'
    ]
  },

  'eulerian-circuit': {
    algorithm: 'eulerian-circuit',
    title: "Hierholzer's Eulerian Circuit Algorithm",
    lines: [
      'vector<int> findEulerianCircuit(int n, vector<vector<int>>& adj, int start) {',
      '    // 1. Degree parity test: all vertices must have even degree',
      '    for (int i = 0; i < n; ++i) {',
      '        if (adj[i].size() % 2 != 0) return {}; // Eulerian circuit impossible',
      '    }',
      '    ',
      '    // 2. Hierholzer algorithm using edge-removal stack',
      '    stack<int> st;',
      '    vector<int> circuit;',
      '    st.push(start);',
      '    ',
      '    while (!st.empty()) {',
      '        int u = st.top();',
      '        if (!adj[u].empty()) {',
      '            int v = adj[u].back();',
      '            adj[u].pop_back();',
      '            st.push(v);',
      '        } else {',
      '            circuit.push_back(u);',
      '            st.pop();',
      '        }',
      '    }',
      '    reverse(circuit.begin(), circuit.end());',
      '    return circuit;',
      '}'
    ]
  },

  'cheapest-flights': {
    algorithm: 'cheapest-flights',
    title: 'Cheapest Flights Within K Stops (LeetCode 787)',
    lines: [
      'int findCheapestPrice(int n, vector<vector<int>>& flights, int src, int dst, int k) {',
      '    vector<vector<pair<int, int>>> adj(n);',
      '    for (auto& f : flights) adj[f[0]].push_back({f[1], f[2]});',
      '    ',
      '    queue<tuple<int, int, int>> q; // {stops, city, cost}',
      '    vector<int> minCost(n, 1e9);',
      '    q.push({0, src, 0});',
      '    minCost[src] = 0;',
      '    ',
      '    while (!q.empty()) {',
      '        auto [stops, u, cost] = q.front(); q.pop();',
      '        if (stops > k) continue; // Exceeded maximum stop budget',
      '        ',
      '        for (auto& [v, price] : adj[u]) {',
      '            if (cost + price < minCost[v]) {',
      '                minCost[v] = cost + price;',
      '                q.push({stops + 1, v, cost + price});',
      '            }',
      '        }',
      '    }',
      '    return minCost[dst] == 1e9 ? -1 : minCost[dst];',
      '}'
    ]
  },

  'covid-spread': {
    algorithm: 'covid-spread',
    title: 'COVID-19 Social Contact Spread & Quarantine',
    lines: [
      'int trackCovidSpread(int n, const vector<vector<int>>& adj, const vector<int>& p0) {',
      '    vector<bool> infected(n, false);',
      '    queue<int> q;',
      '    for (int p : p0) {',
      '        infected[p] = true;',
      '        q.push(p);',
      '    }',
      '    int days = 0;',
      '    ',
      '    while (!q.empty()) {',
      '        int sz = q.size();',
      '        bool newlyInfected = false;',
      '        for (int i = 0; i < sz; ++i) {',
      '            int u = q.front(); q.pop();',
      '            for (int v : adj[u]) {',
      '                if (!infected[v]) {',
      '                    infected[v] = true;',
      '                    q.push(v);',
      '                    newlyInfected = true;',
      '                }',
      '            }',
      '        }',
      '        if (newlyInfected) days++;',
      '    }',
      '    return days;',
      '}'
    ]
  },

  'course-schedule': {
    algorithm: 'course-schedule',
    title: "Course Schedule I - canFinish (LeetCode 207)",
    lines: [
      'bool canFinishCourses(int n, vector<vector<int>>& prereqs, vector<int>& order) {',
      '    vector<vector<int>> adj(n);',
      '    vector<int> inDegree(n, 0);',
      '    for (auto& p : prereqs) {',
      '        adj[p[1]].push_back(p[0]); // prereq -> course',
      '        inDegree[p[0]]++;',
      '    }',
      '    ',
      '    queue<int> q;',
      '    for (int i = 0; i < n; ++i) {',
      '        if (inDegree[i] == 0) q.push(i); // Zero prerequisite courses',
      '    }',
      '    ',
      '    while (!q.empty()) {',
      '        int u = q.front(); q.pop();',
      '        order.push_back(u);',
      '        for (int v : adj[u]) {',
      '            if (--inDegree[v] == 0) {',
      '                q.push(v); // Prerequisite satisfied',
      '            }',
      '        }',
      '    }',
      '    return order.size() == n; // Valid DAG schedule if size matches',
      '}'
    ]
  },

  'course-schedule-2': {
    algorithm: 'course-schedule-2',
    title: 'Course Schedule II - findOrder (LeetCode 210)',
    lines: [
      'vector<int> findOrder(int numCourses, vector<vector<int>>& prerequisites) {',
      '    vector<vector<int>> adj(numCourses);',
      '    vector<int> inDegree(numCourses, 0);',
      '    for (auto& p : prerequisites) {',
      '        adj[p[1]].push_back(p[0]); // p[1] is prerequisite for p[0]',
      '        inDegree[p[0]]++;',
      '    }',
      '    ',
      '    queue<int> q;',
      '    for (int i = 0; i < numCourses; ++i) {',
      '        if (inDegree[i] == 0) q.push(i);',
      '    }',
      '    ',
      '    vector<int> ans;',
      '    while (!q.empty()) {',
      '        int u = q.front(); q.pop();',
      '        ans.push_back(u);',
      '        for (int v : adj[u]) {',
      '            if (--inDegree[v] == 0) {',
      '                q.push(v);',
      '            }',
      '        }',
      '    }',
      '    ',
      '    if (ans.size() == numCourses) return ans; // Valid graduation sequence',
      '    return {}; // Cycle detected: cannot graduate, return [] per LC 210',
      '}'
    ]
  },

  'word-ladder': {
    algorithm: 'word-ladder',
    title: 'Word Ladder (LeetCode 127 • Shortest Transformation BFS)',
    lines: [
      'int ladderLength(string beginWord, string endWord, vector<string>& wordList) {',
      '    unordered_set<string> dict(wordList.begin(), wordList.end());',
      '    if (dict.find(endWord) == dict.end()) return 0; // Target unreachable',
      '    ',
      '    queue<pair<string, int>> q; // {currentWord, level/steps}',
      '    q.push({beginWord, 1});',
      '    dict.erase(beginWord);',
      '    ',
      '    while (!q.empty()) {',
      '        auto [word, level] = q.front(); q.pop();',
      '        ',
      '        if (word == endWord) return level; // Reached endWord in minimal steps!',
      '        ',
      '        for (int i = 0; i < word.length(); ++i) {',
      '            char originalChar = word[i];',
      '            for (char ch = \'a\'; ch <= \'z\'; ++ch) {',
      '                word[i] = ch;',
      '                if (dict.count(word)) {',
      '                    dict.erase(word); // Mark visited to avoid revisiting',
      '                    q.push({word, level + 1});',
      '                }',
      '            }',
      '            word[i] = originalChar; // Restore for next index mutation',
      '        }',
      '    }',
      '    return 0; // No valid transformation sequence exists',
      '}'
    ]
  },

  'word-search': {
    algorithm: 'word-search',
    title: 'Word Search (LeetCode 79 • 2D Grid DFS Backtracking)',
    lines: [
      'bool dfs(vector<vector<char>>& board, string& word, int idx, int r, int c) {',
      '    if (idx == word.length()) return true; // All characters matched',
      '    ',
      '    if (r < 0 || r >= board.size() || c < 0 || c >= board[0].size() || board[r][c] != word[idx]) {',
      '        return false; // Out of bounds, visited (#), or character mismatch',
      '    }',
      '    ',
      '    char temp = board[r][c];',
      '    board[r][c] = \'#\'; // Mark cell visited in active recursion path',
      '    ',
      '    // Explore 4 directions: Down, Up, Right, Left',
      '    bool found = dfs(board, word, idx + 1, r + 1, c) ||',
      '                 dfs(board, word, idx + 1, r - 1, c) ||',
      '                 dfs(board, word, idx + 1, r, c + 1) ||',
      '                 dfs(board, word, idx + 1, r, c - 1);',
      '                 ',
      '    board[r][c] = temp; // Backtrack: restore cell for other search branches',
      '    return found;',
      '}',
      'bool exist(vector<vector<char>>& board, string word) {',
      '    for (int i = 0; i < board.size(); ++i) {',
      '        for (int j = 0; j < board[0].size(); ++j) {',
      '            if (board[i][j] == word[0] && dfs(board, word, 0, i, j)) {',
      '                return true; // Word found starting at (i, j)',
      '            }',
      '        }',
      '    }',
      '    return false; // Word does not exist on board',
      '}'
    ]
  }
};
