/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { AlgorithmId } from '../types';

export interface CppSnippet {
  code: string[];
  lineDescriptions: Record<number, string>;
}

export const CPP_SNIPPETS: Record<AlgorithmId, CppSnippet> = {
  'reverse-list': {
    code: [
      'ListNode* reverseList(ListNode* head) {',
      '    ListNode* prev = nullptr;',
      '    ListNode* curr = head;',
      '    while (curr != nullptr) {',
      '        ListNode* nextNode = curr->next; // Cache next',
      '        curr->next = prev;              // Rewire pointer',
      '        prev = curr;                    // Shift prev forward',
      '        curr = nextNode;                // Shift curr forward',
      '    }',
      '    return prev;                        // New head node',
      '}',
    ],
    lineDescriptions: {
      1: 'Function execution started with the input head node.',
      2: 'Initialize `prev` to `nullptr` (acts as the boundary of our reversed segment).',
      3: 'Set `curr` pointer to the starting node `head`.',
      4: 'Loop until `curr` pointer is null, processing each node in-place.',
      5: 'Cache `nextNode = curr->next` to prevent losing the remainder of the list.',
      6: 'Rewire `curr->next` backward to point to `prev`. The forward link is broken!',
      7: 'Advance `prev` forward to the current node.',
      8: 'Advance `curr` forward to the cached `nextNode`.',
      9: 'Cycle iteration complete. Re-checking loop condition.',
      10: 'Loop terminated. `prev` now points to the new head of the reversed list.',
    },
  },
  'reverse-list-ii': {
    code: [
      'ListNode* reverseBetween(ListNode* head, int left, int right) {',
      '    ListNode dummy(-1, head); // Sentinel node',
      '    ListNode* prev = &dummy;',
      '    for (int i = 1; i < left; ++i) prev = prev->next; // Move to pre-reversal',
      '    ListNode* curr = prev->next;',
      '    for (int i = 0; i < right - left; ++i) {',
      '        ListNode* nextNode = curr->next;',
      '        curr->next = nextNode->next;  // Sever & bypass nextNode',
      '        nextNode->next = prev->next;  // Insert nextNode at reversed head',
      '        prev->next = nextNode;        // Stitch subsegment to prev',
      '    }',
      '    return dummy.next;',
      '}',
    ],
    lineDescriptions: {
      1: 'Function started with sublist boundaries `left` and `right`.',
      2: 'Create sentinel `dummy` pointing to `head` to handle cases where `left = 1`.',
      3: 'Initialize `prev` pointing to `dummy`.',
      4: 'Advance `prev` until it is positioned directly before the reversal boundary.',
      5: 'Position `curr` to point to the first node to be reversed (`prev->next`).',
      6: 'Loop `right - left` times, peeling nodes off and moving them to the front.',
      7: 'Cache `nextNode = curr->next` which will be shifted to the front of sublist.',
      8: 'Bypass `nextNode` by rewiring `curr->next` to `nextNode->next`.',
      9: 'Connect `nextNode->next` to the node currently at the front (`prev->next`).',
      10: 'Stitch `prev->next` to point to `nextNode` (new front of the reversed segment).',
      11: 'Completed subsegment in-place shifting for this cycle iteration.',
      12: 'Return the fully rewired list starting at `dummy.next`.',
    },
  },
  'swap-pairs': {
    code: [
      'ListNode* swapPairs(ListNode* head) {',
      '    ListNode dummy(-1, head);',
      '    ListNode* prev = &dummy;',
      '    while (prev->next && prev->next->next) {',
      '        ListNode* first = prev->next;',
      '        ListNode* second = first->next;',
      '        first->next = second->next; // Bypass second',
      '        second->next = first;       // Wire second to first',
      '        prev->next = second;        // Connect prev to second',
      '        prev = first;               // Move prev forward',
      '    }',
      '    return dummy.next;',
      '}',
    ],
    lineDescriptions: {
      1: 'Function started to swap adjacent pairs.',
      2: 'Setup sentinel `dummy` pointing to `head` to anchor our output.',
      3: 'Initialize `prev` pointing to `dummy`. It tracks the tail of the sorted portion.',
      4: 'Check if there are at least two nodes remaining to swap.',
      5: 'Label the first node of the pair as `first`.',
      6: 'Label the second node of the pair as `second`.',
      7: 'Rewire `first->next` to point past `second` (to `second->next`).',
      8: 'Rewire `second->next` backwards to point to `first`.',
      9: 'Connect `prev->next` to `second`, completing the local pairwise swap.',
      10: 'Move `prev` forward by two steps to `first` (the new tail of swapped segment).',
      11: 'Iteration finished, checking next candidate pair.',
      12: 'Return the swapped list starting at `dummy.next`.',
    },
  },
  'reverse-k-group': {
    code: [
      'ListNode* reverseKGroup(ListNode* head, int k) {',
      '    ListNode dummy(-1, head);',
      '    ListNode* groupPrev = &dummy;',
      '    while (true) {',
      '        ListNode* kth = getKth(groupPrev, k); // Find boundary',
      '        if (!kth) break;                      // Remaining is < k',
      '        ListNode* groupNext = kth->next;',
      '        ListNode* prev = groupNext;           // Reverse group in-place',
      '        ListNode* curr = groupPrev->next;',
      '        while (curr != groupNext) {',
      '            ListNode* nextNode = curr->next;',
      '            curr->next = prev;',
      '            prev = curr;',
      '            curr = nextNode;',
      '        }',
      '        ListNode* temp = groupPrev->next;     // Re-stitch boundaries',
      '        groupPrev->next = kth;',
      '        groupPrev = temp;',
      '    }',
      '    return dummy.next;',
      '}',
    ],
    lineDescriptions: {
      1: 'Function started to reverse nodes in groups of `k`.',
      2: 'Setup sentinel `dummy` pointing to `head`.',
      3: 'Initialize `groupPrev` pointing to `dummy`. It tracks the node before the current k-group.',
      4: 'Enter main group reversal loop.',
      5: 'Advance to find the k-th node from `groupPrev`.',
      6: 'If fewer than `k` nodes remain, terminate. Remaining nodes stay as is.',
      7: 'Cache `groupNext = kth->next`, the starting node of the subsequent group.',
      8: 'Initialize `prev = groupNext` so the first node of this group points to the next group.',
      9: 'Initialize `curr = groupPrev->next`, which points to the start of the current k-group.',
      10: 'Run inner reversal loop to reverse pointers within the k-group boundaries.',
      11: 'Cache `nextNode = curr->next` to preserve list reference.',
      12: 'Set `curr->next = prev`, rewiring the node to point to the current reversed portion.',
      13: 'Shift `prev` forward to `curr`.',
      14: 'Shift `curr` forward to `nextNode`.',
      15: 'Reversal of this k-group completed.',
      16: 'Cache `temp = groupPrev->next`, which is the old group start (new group tail).',
      17: 'Link `groupPrev->next` to `kth` (the new head of this reversed k-group).',
      18: 'Advance `groupPrev` forward to `temp` (the tail of the newly reversed group).',
      19: 'Loop finished, scanning for the next group.',
      20: 'Return full list beginning at `dummy.next`.',
    },
  },
  'merge-two': {
    code: [
      'ListNode* mergeTwoLists(ListNode* l1, ListNode* l2) {',
      '    ListNode dummy(-1);',
      '    ListNode* tail = &dummy;',
      '    while (l1 && l2) {',
      '        if (l1->val <= l2->val) {',
      '            tail->next = l1; // Append l1',
      '            l1 = l1->next;   // Shift l1',
      '        } else {',
      '            tail->next = l2; // Append l2',
      '            l2 = l2->next;   // Shift l2',
      '        }',
      '        tail = tail->next;   // Advance tail',
      '    }',
      '    tail->next = l1 ? l1 : l2; // Stitch remainder',
      '    return dummy.next;',
      '}',
    ],
    lineDescriptions: {
      1: 'Merge function started with list heads `l1` and `l2`.',
      2: 'Create sentinel `dummy` node to build the new merged list.',
      3: 'Initialize pointer `tail` pointing to `dummy`. `tail` always points to the merged end.',
      4: 'Loop while both `l1` and `l2` have remaining nodes to compare.',
      5: 'Compare values: check if `l1->val <= l2->val`.',
      6: 'Since `l1` is smaller or equal, sew `tail->next` to `l1`.',
      7: 'Advance `l1` to the next node in its list.',
      8: 'Since `l2` is smaller, sew `tail->next` to `l2`.',
      9: 'Advance `l2` to the next node in its list.',
      10: 'Complete conditional branch.',
      11: 'Advance the `tail` pointer to the newly appended node.',
      12: 'Finished current comparison step.',
      13: 'At least one list is empty. Terminated comparisons.',
      14: 'Stitch any remaining non-empty nodes from `l1` or `l2` directly to `tail->next`.',
      15: 'Return the merged list starting from `dummy.next`.',
    },
  },
  'add-two': {
    code: [
      'ListNode* addTwoNumbers(ListNode* l1, ListNode* l2) {',
      '    ListNode dummy(-1);',
      '    ListNode* curr = &dummy;',
      '    int carry = 0;',
      '    while (l1 || l2 || carry) {',
      '        int val1 = l1 ? l1->val : 0;',
      '        int val2 = l2 ? l2->val : 0;',
      '        int sum = val1 + val2 + carry; // Add digits',
      '        carry = sum / 10;              // Compute carry',
      '        curr->next = new ListNode(sum % 10);',
      '        curr = curr->next;             // Advance digit',
      '        if (l1) l1 = l1->next;',
      '        if (l2) l2 = l2->next;',
      '    }',
      '    return dummy.next;',
      '}',
    ],
    lineDescriptions: {
      1: 'Function started to add two reversed linked list digits.',
      2: 'Create sentinel `dummy` to build the sum linked list.',
      3: 'Initialize `curr` pointing to `dummy`. It will append each digit node.',
      4: 'Initialize `carry` integer to `0`.',
      5: 'Loop while there is a node in `l1`, `l2`, or a remaining non-zero `carry`.',
      6: 'Extract digit `val1` from `l1`, default to `0` if list is already exhausted.',
      7: 'Extract digit `val2` from `l2`, default to `0` if list is already exhausted.',
      8: 'Calculate `sum` as `val1 + val2 + carry`.',
      9: 'Determine new `carry = sum / 10` (will be either 0 or 1).',
      10: 'Create a new node with value `sum % 10` and append to `curr->next`.',
      11: 'Advance `curr` to point to the newly added sum node.',
      12: 'If `l1` is not exhausted, advance `l1 = l1->next`.',
      13: 'If `l2` is not exhausted, advance `l2 = l2->next`.',
      14: 'Completed addition for this column.',
      15: 'Return the sum list beginning at `dummy.next`.',
    },
  },
  'merge-k': {
    code: [
      'ListNode* mergeKLists(vector<ListNode*>& lists) {',
      '    if (lists.empty()) return nullptr;',
      '    // We simulate by merging lists pair-by-pair in-place',
      '    while (lists.size() > 1) {',
      '        ListNode* merged = mergeTwoLists(lists[0], lists[1]);',
      '        lists.erase(lists.begin()); // Erase index 0',
      '        lists[0] = merged;          // Overwrite with merged list',
      '    }',
      '    return lists[0];',
      '}',
    ],
    lineDescriptions: {
      1: 'Function started to merge `k` sorted linked lists.',
      2: 'If the input vector is completely empty, return `nullptr`.',
      3: 'Comments explaining the pair-by-pair simulation approach.',
      4: 'Loop while there is more than one list left to merge in our pool.',
      5: 'Call our helper to merge the first two lists (`lists[0]` and `lists[1]`).',
      6: 'Remove the first list (`lists[0]`) from the list collection.',
      7: 'Replace the new index 0 with the merged combination, shrinking the pool.',
      8: 'Completed one round of pair merging.',
      9: 'Only one list remains in the list collection. Return it as the final merged list.',
    },
  },
  'partition-list': {
    code: [
      'ListNode* partition(ListNode* head, int x) {',
      '    ListNode lessHead(-1), greaterHead(-1);',
      '    ListNode* lessTail = &lessHead;',
      '    ListNode* greaterTail = &greaterHead;',
      '    ListNode* curr = head;',
      '    while (curr) {',
      '        if (curr->val < x) {',
      '            lessTail->next = curr;       // Append to Less',
      '            lessTail = lessTail->next;',
      '        } else {',
      '            greaterTail->next = curr;    // Append to Greater',
      '            greaterTail = greaterTail->next;',
      '        }',
      '        curr = curr->next;               // Advance curr',
      '    }',
      '    greaterTail->next = nullptr;         // Sever cycle',
      '    lessTail->next = greaterHead.next;   // Stitch lists',
      '    return lessHead.next;',
      '}',
    ],
    lineDescriptions: {
      1: 'Function started to partition nodes based on value `x`.',
      2: 'Create two sentinel dummy heads: `lessHead` and `greaterHead`.',
      3: 'Initialize `lessTail` pointing to `lessHead`. It will track the tail of smaller values.',
      4: 'Initialize `greaterTail` pointing to `greaterHead`. It tracks the tail of larger or equal values.',
      5: 'Initialize rolling pointer `curr` to `head`.',
      6: 'Loop through each node in the list.',
      7: 'Check if `curr->val < x`.',
      8: 'Value is less than `x`. Connect `lessTail->next` to `curr`.',
      9: 'Advance `lessTail` pointer forward.',
      10: 'Value is greater or equal to `x`. Connect `greaterTail->next` to `curr`.',
      11: 'Advance `greaterTail` pointer forward.',
      12: 'Finished conditional branching.',
      13: 'Advance `curr` to the next node in the original list.',
      14: 'Completed partition loop iteration.',
      15: 'Set `greaterTail->next = nullptr` to sever any lingering trailing links (avoids cycles).',
      16: 'Stitch the end of the smaller list (`lessTail->next`) to the head of the greater list (`greaterHead.next`).',
      17: 'Return the combined partitioned list starting at `lessHead.next`.',
    },
  },
  'remove-duplicates': {
    code: [
      'ListNode* deleteDuplicates(ListNode* head) {',
      '    ListNode* curr = head;',
      '    while (curr && curr->next) {',
      '        if (curr->val == curr->next->val) {',
      '            ListNode* duplicate = curr->next;',
      '            curr->next = duplicate->next; // Bypass duplicate',
      '            delete duplicate;             // Free memory',
      '        } else {',
      '            curr = curr->next;            // Advance curr',
      '        }',
      '    }',
      '    return head;',
      '}',
    ],
    lineDescriptions: {
      1: 'Function started to remove adjacent duplicates from sorted list.',
      2: 'Initialize rolling pointer `curr` to `head`.',
      3: 'Loop while `curr` and its next node exist.',
      4: 'Compare current value with next value: `curr->val == curr->next->val`.',
      5: 'Values are identical. Cache the next node in `duplicate`.',
      6: 'Rewire `curr->next` to point past `duplicate` (to `duplicate->next`). Link bypassed!',
      7: 'Free the memory occupied by the duplicate node.',
      8: 'Values differ, meaning no duplicates here. Safe to advance `curr` to the next node.',
      9: 'Completed branch check.',
      10: 'Completed step execution.',
      11: 'All adjacent duplicate nodes removed.',
      12: 'Return the head of the cleaned list.',
    },
  },
  'remove-duplicates-ii': {
    code: [
      'ListNode* deleteDuplicates(ListNode* head) {',
      '    ListNode dummy(-1, head);',
      '    ListNode* prev = &dummy;',
      '    while (prev->next) {',
      '        ListNode* curr = prev->next;',
      '        if (curr->next && curr->val == curr->next->val) {',
      '            while (curr->next && curr->val == curr->next->val) {',
      '                curr = curr->next; // Find last duplicate node',
      '            }',
      '            prev->next = curr->next; // Bypass all duplicates',
      '        } else {',
      '            prev = prev->next;       // Advance prev',
      '        }',
      '    }',
      '    return dummy.next;',
      '}',
    ],
    lineDescriptions: {
      1: 'Function started to remove all occurrences of duplicate values.',
      2: 'Create sentinel `dummy` pointing to `head` (essential as head itself might be deleted).',
      3: 'Initialize pointer `prev` pointing to `dummy`. It tracks the last verified distinct node.',
      4: 'Loop as long as a successor node `prev->next` exists.',
      5: 'Set `curr` pointing to the node `prev->next`.',
      6: 'Check if there are consecutive duplicate nodes starting at `curr`.',
      7: 'Enter inner loop to advance through the run of identical duplicate values.',
      8: 'Advance `curr` forward to skip the current duplicate node.',
      9: 'Exited inner duplicates loop. `curr` points to the last node in the duplicate run.',
      10: 'Rewire `prev->next = curr->next` to completely bypass and detach the entire duplicate run.',
      11: 'No duplicates detected starting at `curr`. It is distinct, so advance `prev` forward.',
      12: 'Finished conditional branching.',
      13: 'Completed iteration.',
      14: 'Return list with all duplicates removed starting at `dummy.next`.',
    },
  },
  'odd-even': {
    code: [
      'ListNode* oddEvenList(ListNode* head) {',
      '    if (!head) return nullptr;',
      '    ListNode* odd = head;',
      '    ListNode* even = head->next;',
      '    ListNode* evenHead = even;',
      '    while (even && even->next) {',
      '        odd->next = even->next; // Sew odd index nodes',
      '        odd = odd->next;',
      '        even->next = odd->next; // Sew even index nodes',
      '        even = even->next;',
      '    }',
      '    odd->next = evenHead;       // Stitch odd and even lists',
      '    return head;',
      '}',
    ],
    lineDescriptions: {
      1: 'Function started to group odd indices followed by even indices.',
      2: 'If list is completely empty, return `nullptr` immediately.',
      3: 'Initialize `odd` pointer starting at `head`.',
      4: 'Initialize `even` pointer starting at second node `head->next`.',
      5: 'Cache `evenHead = even` to remember the starting point of the even-indexed list.',
      6: 'Loop while `even` and `even->next` are non-null.',
      7: 'Connect `odd->next` to `even->next` (skipping the even node).',
      8: 'Advance `odd` pointer forward to the newly linked odd node.',
      9: 'Connect `even->next` to `odd->next` (skipping the odd node).',
      10: 'Advance `even` pointer forward to the newly linked even node.',
      11: 'Iteration finished, checking for additional indices.',
      12: 'Stitch the end of the odd list (`odd->next`) directly to the cached `evenHead`.',
      13: 'Return the head of the re-ordered list.',
    },
  },
  'rotate-list': {
    code: [
      'ListNode* rotateRight(ListNode* head, int k) {',
      '    if (!head || !head->next || k == 0) return head;',
      '    int len = 1;',
      '    ListNode* tail = head;',
      '    while (tail->next) { tail = tail->next; ++len; } // Get length',
      '    tail->next = head;              // Form a circular ring',
      '    k = k % len;',
      '    int steps = len - k;',
      '    for (int i = 0; i < steps; ++i) tail = tail->next; // Find split',
      '    ListNode* newHead = tail->next;',
      '    tail->next = nullptr;           // Break the circle',
      '    return newHead;',
      '}',
    ],
    lineDescriptions: {
      1: 'Function started to rotate list right by `k` steps.',
      2: 'Return early if list is empty, has 1 node, or rotation `k` is 0.',
      3: 'Initialize length counter `len = 1`.',
      4: 'Initialize `tail` pointer starting at `head`.',
      5: 'Traverse to the end node while calculating the exact length of the list.',
      6: 'Connect `tail->next = head` to close the list in-place into a circular loop.',
      7: 'Reduce `k = k % len` since rotating by multiples of length is a redundant full cycle.',
      8: 'Calculate the split offset `steps = len - k`.',
      9: 'Loop `steps` times to advance `tail` to the node right before the split.',
      10: 'Set `newHead` pointing to the node following the split (`tail->next`).',
      11: 'Sever the circular ring by setting `tail->next = nullptr`.',
      12: 'Return `newHead`, the new start of the rotated list.',
    },
  },
  'delete-node': {
    code: [
      'void deleteNode(ListNode* node) {',
      '    ListNode* nextNode = node->next;',
      '    node->val = nextNode->val;     // Overwrite value',
      '    node->next = nextNode->next;   // Bypass nextNode',
      '    delete nextNode;               // Free memory',
      '}',
    ],
    lineDescriptions: {
      1: 'Function started to delete the given node (no head access provided).',
      2: 'Cache `nextNode = node->next`. We will steal its content and then delete it.',
      3: 'Overwrite `node->val` with `nextNode->val`, copying the value from the successor.',
      4: 'Bypass the successor by linking `node->next` directly to `nextNode->next`. Link deleted!',
      5: 'Deallocate the successor `nextNode`, fully completing the in-place removal of its contents.',
    },
  },
  'remove-nth': {
    code: [
      'ListNode* removeNthFromEnd(ListNode* head, int n) {',
      '    ListNode dummy(-1, head);',
      '    ListNode* fast = &dummy;',
      '    ListNode* slow = &dummy;',
      '    for (int i = 0; i <= n; ++i) fast = fast->next; // Create gap',
      '    while (fast != nullptr) {',
      '        fast = fast->next; // Advance together',
      '        slow = slow->next;',
      '    }',
      '    ListNode* target = slow->next;',
      '    slow->next = target->next; // Bypass target node',
      '    delete target;',
      '    return dummy.next;',
      '}',
    ],
    lineDescriptions: {
      1: 'Function started to remove the n-th node from the end of the list.',
      2: 'Setup sentinel `dummy` pointing to `head` (to safely handle deletion of the head node itself).',
      3: 'Initialize pointer `fast` pointing to `dummy`.',
      4: 'Initialize pointer `slow` pointing to `dummy`.',
      5: 'Advance `fast` forward `n + 1` steps to establish the exact spacing interval.',
      6: 'Loop until `fast` reaches `nullptr` (end of the list).',
      7: 'Advance `fast` forward by one step.',
      8: 'Advance `slow` forward in lockstep, keeping the gap interval constant.',
      9: 'Completed loop. `slow` is now positioned precisely before the target node to delete.',
      10: 'Label `target = slow->next`, the actual node to be removed.',
      11: 'Rewire `slow->next` to point past `target` (to `target->next`). Link bypassed!',
      12: 'Free target node memory.',
      13: 'Return list beginning at `dummy.next`.',
    },
  },
  'flatten-multilevel': {
    code: [
      'Node* flatten(Node* head) {',
      '    Node* curr = head;',
      '    while (curr != nullptr) {',
      '        if (curr->child != nullptr) {',
      '            Node* nextNode = curr->next; // Cache next',
      '            Node* childHead = flatten(curr->child);',
      '            curr->next = childHead;      // Splice child start',
      '            childHead->prev = curr;',
      '            curr->child = nullptr;       // Clear child pointer',
      '            Node* childTail = childHead; // Find child tail',
      '            while (childTail->next != nullptr) childTail = childTail->next;',
      '            childTail->next = nextNode;  // Stitch child tail to next',
      '            if (nextNode != nullptr) nextNode->prev = childTail;',
      '        }',
      '        curr = curr->next;',
      '    }',
      '    return head;',
      '}',
    ],
    lineDescriptions: {
      1: 'Function started to flatten a multilevel doubly linked list in-place.',
      2: 'Initialize rolling pointer `curr` starting at the list `head`.',
      3: 'Loop through the list node by node.',
      4: 'Check if `curr` node has a non-null child pointer pointing to a child subsegment.',
      5: 'Child sub-list exists. Cache the subsequent node `nextNode = curr->next`.',
      6: 'Recursively flatten the child sub-list, obtaining the flattened head `childHead`.',
      7: 'Splice `childHead` into the main line: set `curr->next = childHead`.',
      8: 'Complete the doubly link: set `childHead->prev = curr`.',
      9: 'Clear `curr->child = nullptr` to decouple the child relation from this node.',
      10: 'Initialize `childTail = childHead` to search for the tail of this child chain.',
      11: 'Traverse through the child chain to find its final tail node.',
      12: 'Stitch the child chain’s tail to our cached `nextNode` (`childTail->next = nextNode`).',
      13: 'If `nextNode` exists, complete its backward doubly-link to `childTail` (`nextNode->prev = childTail`).',
      14: 'Completed splicing child sub-list in-place.',
      15: 'Advance `curr` forward to process the remaining nodes.',
      16: 'End of iteration.',
      17: 'Return the flattened doubly linked list beginning at `head`.',
    },
  },
  'reorder-list': {
    code: [
      'void reorderList(ListNode* head) {',
      '    if (!head || !head->next) return;',
      '    // 1. Find the middle of the list',
      '    ListNode* slow = head, *fast = head;',
      '    while (fast && fast->next) {',
      '        slow = slow->next;',
      '        fast = fast->next->next;',
      '    }',
      '    // 2. Reverse the second half of the list',
      '    ListNode* prev = nullptr, *curr = slow;',
      '    while (curr) {',
      '        ListNode* nextNode = curr->next;',
      '        curr->next = prev;',
      '        prev = curr;',
      '        curr = nextNode;',
      '    }',
      '    // 3. Merge the two halves alternatively',
      '    ListNode* first = head, *second = prev;',
      '    while (second->next) {',
      '        ListNode* tmp1 = first->next;',
      '        ListNode* tmp2 = second->next;',
      '        first->next = second;',
      '        second->next = tmp1;',
      '        first = tmp1;',
      '        second = tmp2;',
      '    }',
      '}',
    ],
    lineDescriptions: {
      1: 'Function started to reorder the linked list in-place.',
      2: 'If list is empty or has only one node, no reordering is needed.',
      3: 'Comment: Part 1 - Find the middle using slow & fast pointers.',
      4: 'Initialize slow and fast pointers starting at head.',
      5: 'Loop to find list middle: fast moves double slow\'s speed.',
      6: 'Advance slow by one node.',
      7: 'Advance fast by two nodes.',
      8: 'End loop: slow points to the middle node.',
      9: 'Comment: Part 2 - Reverse the second half of the list.',
      10: 'Initialize reversal pointers: prev to nullptr, curr to slow.',
      11: 'Reversal loop for second half.',
      12: 'Cache nextNode = curr->next.',
      13: 'Rewire curr->next to point back to prev.',
      14: 'Advance prev to curr.',
      15: 'Advance curr to nextNode.',
      16: 'End of reversal: prev points to the head of reversed second half.',
      17: 'Comment: Part 3 - Merge both list halves alternatively.',
      18: 'Set first to head (start of first half) and second to prev (start of reversed second half).',
      19: 'Interleave nodes until the second half reaches its tail.',
      20: 'Cache first half\'s next connection: tmp1 = first->next.',
      21: 'Cache second half\'s next connection: tmp2 = second->next.',
      22: 'Connect first->next to second node.',
      23: 'Connect second->next to tmp1.',
      24: 'Advance first pointer forward to tmp1.',
      25: 'Advance second pointer forward to tmp2.',
      26: 'Completed interleaving iteration.',
      27: 'All nodes successfully merged into interleaved list order.',
    },
  },
  'palindrome-list': {
    code: [
      'bool isPalindrome(ListNode* head) {',
      '    if (!head || !head->next) return true;',
      '    ListNode* slow = head, *fast = head;',
      '    while (fast && fast->next) {',
      '        slow = slow->next;',
      '        fast = fast->next->next;',
      '    }',
      '    ListNode* prev = nullptr, *curr = slow;',
      '    while (curr) {',
      '        ListNode* nextNode = curr->next;',
      '        curr->next = prev;',
      '        prev = curr;',
      '        curr = nextNode;',
      '    }',
      '    ListNode* p1 = head, *p2 = prev;',
      '    while (p2) {',
      '        if (p1->val != p2->val) return false;',
      '        p1 = p1->next;',
      '        p2 = p2->next;',
      '    }',
      '    return true;',
      '}',
    ],
    lineDescriptions: {
      1: 'Function started to check if list is a palindrome.',
      2: 'Empty list or single node is always a valid palindrome.',
      3: 'Initialize fast and slow pointers starting at head.',
      4: 'Find middle node of the list using slow and fast pointers.',
      5: 'Advance slow pointer one step.',
      6: 'Advance fast pointer two steps.',
      7: 'Loop finishes: slow is at the middle.',
      8: 'Initialize sublist reversal: prev as nullptr, curr as slow.',
      9: 'Loop to reverse the second half of the list.',
      10: 'Cache nextNode = curr->next.',
      11: 'Rewire curr->next back to prev.',
      12: 'Advance prev forward to curr.',
      13: 'Advance curr to nextNode.',
      14: 'Reversal of second half completed.',
      15: 'Set p1 to head of first half and p2 to prev (head of reversed second half).',
      16: 'Loop to compare values step-by-step.',
      17: 'If values at p1 and p2 differ, the list is not a palindrome.',
      18: 'Advance p1 forward.',
      19: 'Advance p2 forward.',
      20: 'Completed comparison iteration.',
      21: 'All compared values match. The list is a valid palindrome.',
    },
  },
  'intersection-list': {
    code: [
      'ListNode *getIntersectionNode(ListNode *headA, ListNode *headB) {',
      '    if (!headA || !headB) return nullptr;',
      '    ListNode *pA = headA, *pB = headB;',
      '    while (pA != pB) {',
      '        pA = pA ? pA->next : headB;',
      '        pB = pB ? pB->next : headA;',
      '    }',
      '    return pA;',
      '}',
    ],
    lineDescriptions: {
      1: 'Function started to find the intersection node of two lists.',
      2: 'If either list is null, no intersection is possible.',
      3: 'Initialize traversal pointers pA to headA and pB to headB.',
      4: 'Loop until the two pointers meet (equal address).',
      5: 'Advance pA to its next node, or redirect to headB if it reaches nullptr.',
      6: 'Advance pB to its next node, or redirect to headA if it reaches nullptr.',
      7: 'Finished current comparison iteration.',
      8: 'Pointers meet at intersection node (or both meet at nullptr). Return it.',
    },
  },
};
