/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const CODE_SNIPPETS: Record<string, string[]> = {
  'preorder-rec': [
    'void preorder(Node* root) {',
    '    if (root == nullptr) return;',
    '    ',
    '    print(root->val);',
    '    preorder(root->left);',
    '    preorder(root->right);',
    '}'
  ],
  'preorder-iter': [
    'void preorderIterative(Node* root) {',
    '    if (root == nullptr) return;',
    '    stack<Node*> s;',
    '    s.push(root);',
    '    while (!s.empty()) {',
    '        Node* curr = s.top(); s.pop();',
    '        print(curr->val);',
    '        if (curr->right) s.push(curr->right);',
    '        if (curr->left) s.push(curr->left);',
    '    }',
    '}'
  ],
  'inorder-rec': [
    'void inorder(Node* root) {',
    '    if (root == nullptr) return;',
    '    ',
    '    inorder(root->left);',
    '    print(root->val);',
    '    inorder(root->right);',
    '}'
  ],
  'inorder-iter': [
    'void inorderIterative(Node* root) {',
    '    stack<Node*> s;',
    '    Node* curr = root;',
    '    while (curr != nullptr || !s.empty()) {',
    '        while (curr != nullptr) {',
    '            s.push(curr);',
    '            curr = curr->left;',
    '        }',
    '        curr = s.top(); s.pop();',
    '        print(curr->val);',
    '        curr = curr->right;',
    '    }',
    '}'
  ],
  'postorder-rec': [
    'void postorder(Node* root) {',
    '    if (root == nullptr) return;',
    '    ',
    '    postorder(root->left);',
    '    postorder(root->right);',
    '    print(root->val);',
    '}'
  ],
  'postorder-iter': [
    'void postorderIterative(Node* root) {',
    '    if (root == nullptr) return;',
    '    stack<Node*> s1, s2;',
    '    s1.push(root);',
    '    while (!s1.empty()) {',
    '        Node* curr = s1.top(); s1.pop();',
    '        s2.push(curr);',
    '        if (curr->left) s1.push(curr->left);',
    '        if (curr->right) s1.push(curr->right);',
    '    }',
    '    while (!s2.empty()) {',
    '        print(s2.top()->val); s2.pop();',
    '    }',
    '}'
  ],
  'level-order': [
    'void levelOrder(Node* root) {',
    '    if (root == nullptr) return;',
    '    queue<Node*> q;',
    '    q.push(root);',
    '    while (!q.empty()) {',
    '        Node* curr = q.front(); q.pop();',
    '        print(curr->val);',
    '        if (curr->left) q.push(curr->left);',
    '        if (curr->right) q.push(curr->right);',
    '    }',
    '}'
  ],
  'height': [
    'int getHeight(Node* root) {',
    '    if (root == nullptr) return -1; // Or 0 for node-count height',
    '    ',
    '    int leftHeight = getHeight(root->left);',
    '    int rightHeight = getHeight(root->right);',
    '    ',
    '    return max(leftHeight, rightHeight) + 1;',
    '}'
  ],
  'diameter': [
    'int maxDiameter = 0;',
    'int calculateHeight(Node* root) {',
    '    if (root == nullptr) return 0;',
    '    int leftH = calculateHeight(root->left);',
    '    int rightH = calculateHeight(root->right);',
    '    ',
    '    maxDiameter = max(maxDiameter, leftH + rightH);',
    '    return max(leftH, rightH) + 1;',
    '}'
  ],
  'lca': [
    'Node* findLCA(Node* root, Node* p, Node* q) {',
    '    if (root == nullptr || root == p || root == q) return root;',
    '    ',
    '    Node* leftLCA = findLCA(root->left, p, q);',
    '    Node* rightLCA = findLCA(root->right, p, q);',
    '    ',
    '    if (leftLCA && rightLCA) return root;',
    '    return leftLCA ? leftLCA : rightLCA;',
    '}'
  ],
  'left-view': [
    'void leftViewUtil(Node* root, int level, int& maxLevel) {',
    '    if (root == nullptr) return;',
    '    if (maxLevel < level) {',
    '        print(root->val);',
    '        maxLevel = level;',
    '    }',
    '    leftViewUtil(root->left, level + 1, maxLevel);',
    '    leftViewUtil(root->right, level + 1, maxLevel);',
    '}'
  ],
  'right-view': [
    'void rightViewUtil(Node* root, int level, int& maxLevel) {',
    '    if (root == nullptr) return;',
    '    if (maxLevel < level) {',
    '        print(root->val);',
    '        maxLevel = level;',
    '    }',
    '    rightViewUtil(root->right, level + 1, maxLevel);',
    '    rightViewUtil(root->left, level + 1, maxLevel);',
    '}'
  ],
  'top-view': [
    'void topView(Node* root) {',
    '    if (root == nullptr) return;',
    '    map<int, int> m; // hd -> val',
    '    queue<pair<Node*, int>> q; // node, hd',
    '    q.push({root, 0});',
    '    while (!q.empty()) {',
    '        auto p = q.front(); q.pop();',
    '        Node* curr = p.first; int hd = p.second;',
    '        if (m.find(hd) == m.end()) m[hd] = curr->val;',
    '        if (curr->left) q.push({curr->left, hd - 1});',
    '        if (curr->right) q.push({curr->right, hd + 1});',
    '    }',
    '}'
  ],
  'bottom-view': [
    'void bottomView(Node* root) {',
    '    if (root == nullptr) return;',
    '    map<int, int> m; // hd -> val',
    '    queue<pair<Node*, int>> q; // node, hd',
    '    q.push({root, 0});',
    '    while (!q.empty()) {',
    '        auto p = q.front(); q.pop();',
    '        Node* curr = p.first; int hd = p.second;',
    '        m[hd] = curr->val;',
    '        if (curr->left) q.push({curr->left, hd - 1});',
    '        if (curr->right) q.push({curr->right, hd + 1});',
    '    }',
    '}'
  ],
  'path-sum': [
    'bool hasPathSum(Node* root, int targetSum) {',
    '    if (root == nullptr) return false;',
    '    ',
    '    if (root->left == nullptr && root->right == nullptr) {',
    '        return targetSum == root->val;',
    '    }',
    '    ',
    '    int remaining = targetSum - root->val;',
    '    return hasPathSum(root->left, remaining) || ',
    '           hasPathSum(root->right, remaining);',
    '}'
  ],
  'symmetric': [
    'bool isMirror(Node* t1, Node* t2) {',
    '    if (t1 == nullptr && t2 == nullptr) return true;',
    '    if (t1 == nullptr || t2 == nullptr) return false;',
    '    ',
    '    return (t1->val == t2->val) && ',
    '           isMirror(t1->left, t2->right) && ',
    '           isMirror(t1->right, t2->left);',
    '}'
  ],
  'serialize-deserialize': [
    'string serialize(Node* root) {',
    '    if (root == nullptr) return "#";',
    '    return to_string(root->val) + "," + ',
    '           serialize(root->left) + "," + ',
    '           serialize(root->right);',
    '}',
    '',
    'Node* deserializeHelper(stringstream& ss) {',
    '    string val;',
    '    if (!getline(ss, val, \',\') || val == "#") return nullptr;',
    '    Node* root = new Node(stoi(val));',
    '    root->left = deserializeHelper(ss);',
    '    root->right = deserializeHelper(ss);',
    '    return root;',
    '}'
  ],
  'boundary-traversal': [
    'void traverseBoundary(Node* root) {',
    '    if (!root) return;',
    '    print(root->val);',
    '    printLeftBoundary(root->left);',
    '    printLeaves(root->left);',
    '    printLeaves(root->right);',
    '    printRightBoundary(root->right);',
    '}'
  ],
  'morris-inorder': [
    'void morrisInorder(Node* root) {',
    '    Node* curr = root;',
    '    while (curr != nullptr) {',
    '        if (curr->left == nullptr) {',
    '            visit(curr); curr = curr->right;',
    '        } else {',
    '            Node* prev = curr->left;',
    '            while (prev->right && prev->right != curr)',
    '                prev = prev->right;',
    '            if (prev->right == nullptr) {',
    '                prev->right = curr; curr = curr->left;',
    '            } else {',
    '                prev->right = nullptr; visit(curr);',
    '                curr = curr->right;',
    '            }',
    '        }',
    '    }',
    '}'
  ],
  'burning-tree': [
    'int minTimeToBurnTree(Node* root, int start) {',
    '    // Find start & build parent pointers (BFS)',
    '    unordered_map<Node*, Node*> parentMap;',
    '    Node* target = bfsToMapParents(root, start, parentMap);',
    '    ',
    '    queue<Node*> q; q.push(target);',
    '    unordered_set<Node*> burned; burned.insert(target);',
    '    int time = 0;',
    '    while(!q.empty()) {',
    '        int sz = q.size(); bool spread = false;',
    '        for(int i=0; i<sz; ++i) {',
    '            Node* curr = q.front(); q.pop();',
    '            if (curr->left && !burned.count(curr->left)) {',
    '                burned.insert(curr->left); q.push(curr->left); spread = true;',
    '            }',
    '            if (curr->right && !burned.count(curr->right)) {',
    '                burned.insert(curr->right); q.push(curr->right); spread = true;',
    '            }',
    '            if (parentMap[curr] && !burned.count(parentMap[curr])) {',
    '                burned.insert(parentMap[curr]); q.push(parentMap[curr]); spread = true;',
    '            }',
    '        }',
    '        if (spread) time++;',
    '    }',
    '    return time;',
    '}'
  ]
};
