export const CPP_SNIPPETS: Record<string, string[]> = {
  cpp_01: [
    '// Standard Linear Queue Implementation',
    'class LinearQueue {',
    'private:',
    '    int arr[100];',
    '    int front = 0;',
    '    int rear = 0;',
    '    int capacity = 5;',
    'public:',
    '    bool enqueue(int val) {',
    '        if (rear == capacity) {',
    '            return false; // Queue Overflow',
    '        }',
    '        arr[rear++] = val;',
    '        return true;',
    '    }',
    '    int dequeue() {',
    '        if (front == rear) {',
    '            return -1; // Queue Underflow',
    '        }',
    '        return arr[front++];',
    '    }',
    '    int peek() {',
    '        if (front == rear) return -1;',
    '        return arr[front];',
    '    }',
    '};'
  ],
  cpp_02: [
    '// Design Circular Queue (LeetCode #622)',
    'class MyCircularQueue {',
    'private:',
    '    vector<int> arr;',
    '    int front = 0, rear = 0;',
    '    int count = 0, capacity;',
    'public:',
    '    MyCircularQueue(int k) : capacity(k), arr(k, -1) {}',
    '    ',
    '    bool enQueue(int value) {',
    '        if (isFull()) return false;',
    '        arr[rear] = value;',
    '        rear = (rear + 1) % capacity;',
    '        count++;',
    '        return true;',
    '    }',
    '    ',
    '    bool deQueue() {',
    '        if (isEmpty()) return false;',
    '        arr[front] = -1; // clear element',
    '        front = (front + 1) % capacity;',
    '        count--;',
    '        return true;',
    '    }',
    '    ',
    '    int Front() {',
    '        return isEmpty() ? -1 : arr[front];',
    '    }',
    '    ',
    '    int Rear() {',
    '        if (isEmpty()) return -1;',
    '        int lastIdx = (rear - 1 + capacity) % capacity;',
    '        return arr[lastIdx];',
    '    }',
    '    ',
    '    bool isEmpty() { return count == 0; }',
    '    bool isFull() { return count == capacity; }',
    '};'
  ],
  cpp_03: [
    '// Design Circular Deque (LeetCode #641)',
    'class MyCircularDeque {',
    'private:',
    '    vector<int> arr;',
    '    int front = 0, rear = 0;',
    '    int count = 0, capacity;',
    'public:',
    '    MyCircularDeque(int k) : capacity(k), arr(k, -1) {}',
    '    ',
    '    bool insertFront(int value) {',
    '        if (isFull()) return false;',
    '        front = (front - 1 + capacity) % capacity;',
    '        arr[front] = value;',
    '        count++;',
    '        return true;',
    '    }',
    '    ',
    '    bool insertLast(int value) {',
    '        if (isFull()) return false;',
    '        arr[rear] = value;',
    '        rear = (rear + 1) % capacity;',
    '        count++;',
    '        return true;',
    '    }',
    '    ',
    '    bool deleteFront() {',
    '        if (isEmpty()) return false;',
    '        arr[front] = -1;',
    '        front = (front + 1) % capacity;',
    '        count--;',
    '        return true;',
    '    }',
    '    ',
    '    bool deleteLast() {',
    '        if (isEmpty()) return false;',
    '        rear = (rear - 1 + capacity) % capacity;',
    '        arr[rear] = -1;',
    '        count--;',
    '        return true;',
    '    }',
    '    ',
    '    int getFront() { return isEmpty() ? -1 : arr[front]; }',
    '    int getRear() {',
    '        if (isEmpty()) return -1;',
    '        return arr[(rear - 1 + capacity) % capacity];',
    '    }',
    '    bool isEmpty() { return count == 0; }',
    '    bool isFull() { return count == capacity; }',
    '};'
  ],
  cpp_04: [
    '// Implement Queue using Stacks (LeetCode #232)',
    'class MyQueue {',
    'private:',
    '    stack<int> s1; // For enqueue/push',
    '    stack<int> s2; // For dequeue/peek',
    '    ',
    '    void transfer() {',
    '        while (!s1.empty()) {',
    '            s2.push(s1.top());',
    '            s1.pop();',
    '        }',
    '    }',
    'public:',
    '    void push(int x) {',
    '        s1.push(x);',
    '    }',
    '    ',
    '    int pop() {',
    '        if (s2.empty()) transfer();',
    '        int topVal = s2.top();',
    '        s2.pop();',
    '        return topVal;',
    '    }',
    '    ',
    '    int peek() {',
    '        if (s2.empty()) transfer();',
    '        return s2.top();',
    '    }',
    '    ',
    '    bool empty() {',
    '        return s1.empty() && s2.empty();',
    '    }',
    '};'
  ],
  cpp_05: [
    '// Implement Stack using Queues (LeetCode #225)',
    'class MyStack {',
    'private:',
    '    queue<int> q;',
    'public:',
    '    void push(int x) {',
    '        q.push(x);',
    '        int size = q.size();',
    '        for (int i = 0; i < size - 1; i++) {',
    '            q.push(q.front());',
    '            q.pop();',
    '        }',
    '    }',
    '    ',
    '    int pop() {',
    '        int val = q.front();',
    '        q.pop();',
    '        return val;',
    '    }',
    '    ',
    '    int top() {',
    '        return q.front();',
    '    }',
    '    ',
    '    bool empty() {',
    '        return q.empty();',
    '    }',
    '};'
  ],
  cpp_06: [
    '// Sliding Window Maximum (LeetCode #239)',
    'vector<int> maxSlidingWindow(vector<int>& nums, int k) {',
    '    deque<int> dq; // stores indices',
    '    vector<int> result;',
    '    for (int i = 0; i < nums.size(); ++i) {',
    '        // 1. Remove indices out of current window',
    '        if (!dq.empty() && dq.front() < i - k + 1) {',
    '            dq.pop_front();',
    '        }',
    '        // 2. Maintain decreasing order in deque',
    '        while (!dq.empty() && nums[dq.back()] <= nums[i]) {',
    '            dq.pop_back();',
    '        }',
    '        // 3. Insert current element index',
    '        dq.push_back(i);',
    '        // 4. Record maximum of current window',
    '        if (i >= k - 1) {',
    '            result.push_back(nums[dq.front()]);',
    '        }',
    '    }',
    '    return result;',
    '}'
  ],
  cpp_07: [
    '// Longest Subarray with Abs Diff <= Limit (LeetCode #1438)',
    'int longestSubarray(vector<int>& nums, int limit) {',
    '    deque<int> maxDq, minDq; // store indices',
    '    int left = 0, maxLength = 0;',
    '    for (int right = 0; right < nums.size(); ++right) {',
    '        while (!maxDq.empty() && nums[maxDq.back()] < nums[right])',
    '            maxDq.pop_back();',
    '        while (!minDq.empty() && nums[minDq.back()] > nums[right])',
    '            minDq.pop_back();',
    '        maxDq.push_back(right);',
    '        minDq.push_back(right);',
    '        ',
    '        // If current window exceeds limit, shrink left',
    '        while (nums[maxDq.front()] - nums[minDq.front()] > limit) {',
    '            if (maxDq.front() == left) maxDq.pop_front();',
    '            if (minDq.front() == left) minDq.pop_front();',
    '            left++;',
    '        }',
    '        maxLength = max(maxLength, right - left + 1);',
    '    }',
    '    return maxLength;',
    '}'
  ],
  cpp_08: [
    '// Shortest Subarray with Sum >= K (LeetCode #862)',
    'int shortestSubarray(vector<int>& nums, int k) {',
    '    int n = nums.size();',
    '    vector<long long> prefix(n + 1, 0);',
    '    for (int i = 0; i < n; ++i) prefix[i+1] = prefix[i] + nums[i];',
    '    deque<int> dq; // stores prefix sum indices',
    '    int minLen = n + 1;',
    '    for (int i = 0; i <= n; ++i) {',
    '        while (!dq.empty() && prefix[i] - prefix[dq.front()] >= k) {',
    '            minLen = min(minLen, i - dq.front());',
    '            dq.pop_front();',
    '        }',
    '        while (!dq.empty() && prefix[i] <= prefix[dq.back()]) {',
    '            dq.pop_back();',
    '        }',
    '        dq.push_back(i);',
    '    }',
    '    return minLen > n ? -1 : minLen;',
    '}'
  ],
  cpp_09: [
    '// First Non-Repeating Character in a Stream',
    'string firstNonRepeating(string A) {',
    '    vector<int> freq(26, 0);',
    '    queue<char> q;',
    '    string ans = "";',
    '    for (char ch : A) {',
    '        freq[ch - \'a\']++;',
    '        q.push(ch);',
    '        while (!q.empty() && freq[q.front() - \'a\'] > 1) {',
    '            q.pop();',
    '        }',
    '        if (q.empty()) ans += \'#\';',
    '        else ans += q.front();',
    '    }',
    '    return ans;',
    '}'
  ],
  cpp_10: [
    '// Moving Average from Data Stream (LeetCode #346)',
    'class MovingAverage {',
    'private:',
    '    queue<int> q;',
    '    int size;',
    '    double sum = 0;',
    'public:',
    '    MovingAverage(int k) : size(k) {}',
    '    ',
    '    double next(int val) {',
    '        q.push(val);',
    '        sum += val;',
    '        if (q.size() > size) {',
    '            sum -= q.front();',
    '            q.pop();',
    '        }',
    '        return sum / q.size();',
    '    }',
    '};'
  ],
  cpp_11: [
    '// Reveal Cards In Increasing Order (LeetCode #950)',
    'vector<int> deckRevealedIncreasing(vector<int>& deck) {',
    '    sort(deck.begin(), deck.end());',
    '    int n = deck.size();',
    '    queue<int> q; // stores indices',
    '    for (int i = 0; i < n; ++i) q.push(i);',
    '    vector<int> res(n);',
    '    for (int card : deck) {',
    '        res[q.front()] = card;',
    '        q.pop();',
    '        if (!q.empty()) {',
    '            q.push(q.front());',
    '            q.pop();',
    '        }',
    '    }',
    '    return res;',
    '}'
  ],
  cpp_12: [
    '// Rotting Oranges (LeetCode #994)',
    'int orangesRotting(vector<vector<int>>& grid) {',
    '    int r = grid.size(), c = grid[0].size();',
    '    queue<pair<int, int>> q; // stores [row, col]',
    '    int fresh = 0, mins = 0;',
    '    for (int i = 0; i < r; ++i)',
    '        for (int j = 0; j < c; ++j) {',
    '            if (grid[i][j] == 2) q.push({i, j});',
    '            else if (grid[i][j] == 1) fresh++;',
    '        }',
    '    int dir[4][2] = {{-1,0}, {1,0}, {0,-1}, {0,1}};',
    '    while (!q.empty() && fresh > 0) {',
    '        int sz = q.size();',
    '        for (int i = 0; i < sz; ++i) {',
    '            auto [x, y] = q.front(); q.pop();',
    '            for (auto& d : dir) {',
    '                int nx = x + d[0], ny = y + d[1];',
    '                if (nx>=0 && nx<r && ny>=0 && ny<c && grid[nx][ny]==1) {',
    '                    grid[nx][ny] = 2; fresh--;',
    '                    q.push({nx, ny});',
    '                }',
    '            }',
    '        }',
    '        mins++;',
    '    }',
    '    return fresh == 0 ? mins : -1;',
    '}'
  ],
  cpp_13: [
    '// Gas Station / Circular Tour (LeetCode #134)',
    'int canCompleteCircuit(vector<int>& gas, vector<int>& cost) {',
    '    int totalGas = 0, totalCost = 0;',
    '    int tank = 0, startIdx = 0;',
    '    for (int i = 0; i < gas.size(); ++i) {',
    '        totalGas += gas[i]; totalCost += cost[i];',
    '        tank += gas[i] - cost[i];',
    '        if (tank < 0) {',
    '            startIdx = i + 1; // start from next station',
    '            tank = 0; // reset tank',
    '        }',
    '    }',
    '    return totalGas >= totalCost ? startIdx : -1;',
    '}'
  ],
  cpp_14: [
    '// Task Scheduler (LeetCode #621)',
    'int leastInterval(vector<char>& tasks, int n) {',
    '    unordered_map<char, int> counts;',
    '    for (char t : tasks) counts[t]++;',
    '    priority_queue<int> pq; // max freq',
    '    for (auto& p : counts) pq.push(p.second);',
    '    queue<pair<int, int>> cool; // stores {freq, cool_until}',
    '    int time = 0;',
    '    while (!pq.empty() || !cool.empty()) {',
    '        time++;',
    '        if (!pq.empty()) {',
    '            int freq = pq.top() - 1; pq.pop();',
    '            if (freq > 0) cool.push({freq, time + n});',
    '        }',
    '        if (!cool.empty() && cool.front().second == time) {',
    '            pq.push(cool.front().first); cool.pop();',
    '        }',
    '    }',
    '    return time;',
    '}'
  ],
  cpp_15: [
    '// LRU Cache (LeetCode #146)',
    'class LRUCache {',
    '    int cap; list<int> dll; // Deque storing keys',
    '    unordered_map<int, pair<int, list<int>::iterator>> cache;',
    'public:',
    '    LRUCache(int capacity) : cap(capacity) {}',
    '    int get(int key) {',
    '        if (!cache.count(key)) return -1;',
    '        dll.erase(cache[key].second); // move key to front',
    '        dll.push_front(key);',
    '        cache[key].second = dll.begin();',
    '        return cache[key].first;',
    '    }',
    '    void put(int key, int value) {',
    '        if (cache.count(key)) {',
    '            dll.erase(cache[key].second);',
    '        } else if (dll.size() == cap) {',
    '            int lru = dll.back(); dll.pop_back(); // evict',
    '            cache.erase(lru);',
    '        }',
    '        dll.push_front(key);',
    '        cache[key] = {value, dll.begin()};',
    '    }',
    '};'
  ],
  cpp_16: [
    '// Binary Tree Level Order Traversal (LeetCode #102)',
    'vector<vector<int>> levelOrder(TreeNode* root) {',
    '    vector<vector<int>> ans;',
    '    if (!root) return ans;',
    '    queue<TreeNode*> q;',
    '    q.push(root);',
    '    while (!q.empty()) {',
    '        int sz = q.size();',
    '        vector<int> level;',
    '        for (int i = 0; i < sz; ++i) {',
    '            TreeNode* curr = q.front(); q.pop();',
    '            level.push_back(curr->val);',
    '            if (curr->left) q.push(curr->left);',
    '            if (curr->right) q.push(curr->right);',
    '        }',
    '        ans.push_back(level);',
    '    }',
    '    return ans;',
    '}'
  ],
  cpp_17: [
    '// Number of Recent Calls (LeetCode #933)',
    'class RecentCounter {',
    '    queue<int> q;',
    'public:',
    '    RecentCounter() {}',
    '    int ping(int t) {',
    '        q.push(t);',
    '        while (!q.empty() && q.front() < t - 3000) {',
    '            q.pop();',
    '        }',
    '        return q.size();',
    '    }',
    '};'
  ],
  cpp_18: [
    '// Bounded Blocking Queue (LeetCode #1188)',
    'class BoundedBlockingQueue {',
    '    mutex mtx; condition_variable cv_enq, cv_deq;',
    '    queue<int> q; int cap;',
    'public:',
    '    BoundedBlockingQueue(int capacity) : cap(capacity) {}',
    '    void enqueue(int element) {',
    '        unique_lock<mutex> lock(mtx);',
    '        cv_enq.wait(lock, [this]() { return q.size() < cap; });',
    '        q.push(element);',
    '        cv_deq.notify_one();',
    '    }',
    '    int dequeue() {',
    '        unique_lock<mutex> lock(mtx);',
    '        cv_deq.wait(lock, [this]() { return !q.empty(); });',
    '        int val = q.front(); q.pop();',
    '        cv_enq.notify_one();',
    '        return val;',
    '    }',
    '};'
  ],
  cpp_19: [
    '// Queue Reconstruction by Height (LeetCode #406)',
    'vector<vector<int>> reconstructQueue(vector<vector<int>>& people) {',
    '    sort(people.begin(), people.end(), [](const vector<int>& a, const vector<int>& b) {',
    '        return a[0] == b[0] ? a[1] < b[1] : a[0] > b[0];',
    '    });',
    '    vector<vector<int>> res;',
    '    for (const auto& p : people) {',
    '        res.insert(res.begin() + p[1], p);',
    '    }',
    '    return res;',
    '}'
  ],
  cpp_20: [
    '// 0-1 BFS Shortest Path using Deque',
    'vector<int> zeroOneBFS(vector<vector<pair<int, int>>>& adj, int start) {',
    '    vector<int> dist(adj.size(), INT_MAX);',
    '    deque<int> dq;',
    '    dist[start] = 0; dq.push_front(start);',
    '    while (!dq.empty()) {',
    '        int u = dq.front(); dq.pop_front();',
    '        for (auto& edge : adj[u]) {',
    '            int v = edge.first, w = edge.second;',
    '            if (dist[u] + w < dist[v]) {',
    '                dist[v] = dist[u] + w;',
    '                if (w == 0) dq.push_front(v);',
    '                else dq.push_back(v);',
    '            }',
    '        }',
    '    }',
    '    return dist;',
    '}'
  ]
};
