import { useState, useEffect, useRef } from 'react';
import { QueueProblem, SimulationStep } from './types';
import { QUEUE_PROBLEMS } from './data/queueProblems';
import { generateSimulationSteps } from './algorithms/queueAlgorithms';
import { Header } from './components/Header';
import { QuestionCard } from './components/QuestionCard';
import { QueueCanvas } from './components/QueueCanvas';
import { TraceAndStatePanel } from './components/TraceAndStatePanel';
import { SimulationControls } from './components/SimulationControls';
import { CategorySelector } from './components/CategorySelector';
import { HelpCircle, Info, Sparkles } from 'lucide-react';

export default function App() {
  // Problem sequence state
  const [currentProblem, setCurrentProblem] = useState<QueueProblem>(QUEUE_PROBLEMS[0]);
  const [capacity, setCapacity] = useState<number>(5);

  // Sub-classification category state
  const [activeCategory, setActiveCategory] = useState<string>(QUEUE_PROBLEMS[0].category);

  // Simulation inputs
  const [inputs, setInputs] = useState<Record<string, any>>(QUEUE_PROBLEMS[0].defaultInput);

  // Active steps list generated by simulation engine
  const [steps, setSteps] = useState<SimulationStep[]>([]);
  const [currentStepIndex, setCurrentStepIndex] = useState<number>(0);

  // Playback control states
  const [isPlaying, setIsPlaying] = useState<boolean>(false);
  const [speed, setSpeed] = useState<number>(1); // 0.5, 1, 2

  // Timer reference for safe cleanup
  const timerRef = useRef<NodeJS.Timeout | null>(null);

  // Load problem defaults and trigger initial simulation
  const loadProblem = (prob: QueueProblem) => {
    setCurrentProblem(prob);
    setActiveCategory(prob.category);
    setIsPlaying(false);
    
    // Set custom capacity if applicable
    const initialCapacity = prob.id === '01' || prob.id === '02' || prob.id === '03' ? capacity : 5;
    const defaultInps = { ...prob.defaultInput, capacity: initialCapacity };
    setInputs(defaultInps);

    const generatedSteps = generateSimulationSteps(prob.id, defaultInps);
    setSteps(generatedSteps);
    setCurrentStepIndex(0);
  };

  const handleSelectProblemId = (id: string) => {
    const selected = QUEUE_PROBLEMS.find((p) => p.id === id);
    if (selected) {
      loadProblem(selected);
    }
  };

  const handleSelectCategory = (category: string) => {
    const firstInCat = QUEUE_PROBLEMS.find((p) => p.category === category);
    if (firstInCat) {
      loadProblem(firstInCat);
    }
  };

  // Re-simulate with active user inputs
  const triggerSimulation = () => {
    const simulationInputs = { ...inputs, capacity };
    const generatedSteps = generateSimulationSteps(currentProblem.id, simulationInputs);
    setSteps(generatedSteps);
    setCurrentStepIndex(0);
    setIsPlaying(false);
  };

  // Preset fill action based on problem context
  const handleRandomFill = () => {
    setIsPlaying(false);
    let randInps: Record<string, any> = {};

    switch (currentProblem.id) {
      case '01':
      case '02':
      case '03': {
        const ops = ['Enqueue', 'Dequeue', 'Peek'];
        const values = [5, 12, 18, 25, 30, 42];
        const countOps = 5 + Math.floor(Math.random() * 3);
        const seq: string[] = [];
        for (let i = 0; i < countOps; i++) {
          const o = ops[Math.floor(Math.random() * ops.length)];
          if (o === 'Enqueue' || o === 'enq' || o === 'insertLast') {
            const val = values[Math.floor(Math.random() * values.length)];
            seq.push(currentProblem.id === '03' ? `insertLast(${val})` : `enq(${val})`);
          } else {
            seq.push(currentProblem.id === '03' ? 'deleteFront()' : 'deq()');
          }
        }
        randInps = { operations: seq.join(', ') };
        break;
      }
      case '06':
      case '07':
      case '08':
      case '11': {
        const arr = Array.from({ length: 8 }, () => Math.floor(Math.random() * 18) + (currentProblem.id === '08' ? -5 : 1));
        randInps = {
          array: arr.join(','),
          k: 3,
          limit: 4,
          size: 3,
        };
        break;
      }
      case '10': {
        const arr = Array.from({ length: 6 }, () => Math.floor(Math.random() * 12) + 1);
        randInps = { array: arr.join(','), size: 3 };
        break;
      }
      default:
        randInps = currentProblem.defaultInput;
    }

    setInputs(randInps);
    setTimeout(() => {
      const generated = generateSimulationSteps(currentProblem.id, { ...randInps, capacity });
      setSteps(generated);
      setCurrentStepIndex(0);
    }, 50);
  };

  const handleResetCase = () => {
    setIsPlaying(false);
    setInputs(currentProblem.defaultInput);
    setTimeout(() => {
      const generated = generateSimulationSteps(currentProblem.id, { ...currentProblem.defaultInput, capacity });
      setSteps(generated);
      setCurrentStepIndex(0);
    }, 50);
  };

  // Auto-simulate on mount
  useEffect(() => {
    loadProblem(QUEUE_PROBLEMS[0]);
  }, []);

  // Sync capacity modifications
  useEffect(() => {
    if (['01', '02', '03'].includes(currentProblem.id)) {
      triggerSimulation();
    }
  }, [capacity]);

  // Handle auto playback interval
  useEffect(() => {
    if (isPlaying) {
      const ms = speed === 0.5 ? 1800 : speed === 2 ? 450 : 900;
      timerRef.current = setInterval(() => {
        setCurrentStepIndex((prev) => {
          if (prev < steps.length - 1) {
            return prev + 1;
          } else {
            setIsPlaying(false);
            return prev;
          }
        });
      }, ms);
    } else {
      if (timerRef.current) {
        clearInterval(timerRef.current);
      }
    }

    return () => {
      if (timerRef.current) {
        clearInterval(timerRef.current);
      }
    };
  }, [isPlaying, steps, speed]);

  // Navigation handlers
  const handlePrevStep = () => {
    setIsPlaying(false);
    setCurrentStepIndex((prev) => Math.max(0, prev - 1));
  };

  const handleNextStep = () => {
    setIsPlaying(false);
    setCurrentStepIndex((prev) => Math.min(steps.length - 1, prev + 1));
  };

  const handleResetStep = () => {
    setIsPlaying(false);
    setCurrentStepIndex(0);
  };

  // Keyboard navigation shortcuts
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      // Ignore shortcuts if user is typing in forms/inputs
      const tag = e.target ? (e.target as HTMLElement).tagName.toUpperCase() : '';
      if (tag === 'INPUT' || tag === 'SELECT' || tag === 'TEXTAREA') {
        return;
      }

      switch (e.code) {
        case 'Space':
          e.preventDefault();
          setIsPlaying((prev) => !prev);
          break;
        case 'ArrowLeft':
          e.preventDefault();
          handlePrevStep();
          break;
        case 'ArrowRight':
          e.preventDefault();
          handleNextStep();
          break;
        case 'KeyR':
          e.preventDefault();
          handleResetStep();
          break;
        default:
          break;
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [steps]);

  const activeStep = steps[currentStepIndex] || {
    stepIndex: 0,
    line: 1,
    explanation: 'Initialized workspace.',
    logs: [],
  };

  return (
    <div className="flex flex-col h-screen max-h-screen overflow-hidden bg-[#FAF9F6] text-slate-800">
      {/* Dynamic SEO sync */}
      <Header
        currentProblem={currentProblem}
        onSelectProblem={handleSelectProblemId}
        capacity={capacity}
        onCapacityChange={setCapacity}
        onRandomFill={handleRandomFill}
        onReset={handleResetCase}
      />

      {/* Category selector visual segmented pills */}
      <CategorySelector
        activeCategory={activeCategory}
        onSelectCategory={handleSelectCategory}
      />

      {/* Main Single-Viewport Layout Grid */}
      <main className="flex-1 overflow-hidden p-3 grid grid-cols-12 gap-3 max-w-7xl mx-auto w-full">
        {/* Left Column (7 cols): Canvas, Console, Question Info & Controls */}
        <section className="col-span-7 flex flex-col gap-3 min-h-0 h-full justify-between">
          {/* Top Question and test cases parameters card */}
          <QuestionCard
            problem={currentProblem}
            inputs={inputs}
            onInputsChange={setInputs}
            onSimulate={triggerSimulation}
            onResetCase={handleResetCase}
          />

          {/* Core visual Interactive Canvas */}
          <div className="flex-1 min-h-0">
            <QueueCanvas algorithmId={currentProblem.id} step={activeStep} />
          </div>

          {/* Docked playback scrubber & operational explanation */}
          <SimulationControls
            currentStep={currentStepIndex}
            totalSteps={steps.length}
            isPlaying={isPlaying}
            speed={speed}
            explanation={activeStep.explanation}
            onStepChange={setCurrentStepIndex}
            onPlayPause={() => setIsPlaying(!isPlaying)}
            onPrev={handlePrevStep}
            onNext={handleNextStep}
            onReset={handleResetStep}
            onSpeedChange={setSpeed}
          />
        </section>

        {/* Right Column (5 cols): Synchronized C++ Trace & State Inspector */}
        <section className="col-span-5 flex flex-col min-h-0 h-full">
          <TraceAndStatePanel
            algorithmId={currentProblem.id}
            cppSnippetId={currentProblem.cppSnippetId}
            step={activeStep}
          />

          {/* Minimalist Tip Box to Flatten Depth and keep single-view pristine */}
          <div className="mt-3 bg-amber-50/70 border border-amber-100 rounded-xl p-2.5 flex items-start gap-2 text-[11px] text-amber-800 shrink-0 font-sans">
            <Sparkles className="w-4 h-4 text-amber-600 shrink-0 mt-0.5" />
            <div>
              <strong className="font-semibold text-amber-900 block uppercase tracking-wider text-[9px] mb-0.5">
                Pro Keyboard Shortcuts:
              </strong>
              Press <kbd className="bg-amber-100/80 px-1 border border-amber-300 rounded font-bold font-mono">Space</kbd> to Play/Pause,{' '}
              <kbd className="bg-amber-100/80 px-1 border border-amber-300 rounded font-bold font-mono">←</kbd> /{' '}
              <kbd className="bg-amber-100/80 px-1 border border-amber-300 rounded font-bold font-mono">→</kbd> to step manually, and{' '}
              <kbd className="bg-amber-100/80 px-1 border border-amber-300 rounded font-bold font-mono">R</kbd> to reset.
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
